<?php
/**
 * TrustScript Order Registry
 * This class manages a custom database table that tracks which orders/products have been published as reviews.
 * This allows us to efficiently check if an order has already been processed, which is crucial for avoiding duplicates
 * and ensuring idempotency, especially when handling webhooks and multi-product orders.
 * 
 * @package TrustScript
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class TrustScript_Order_Registry {

	/**
	 * Table slug (without prefix) for the order registry.
	 * The full table name will be {$wpdb->prefix}trustscript_published_orders.
	 */
	const TABLE_SLUG = 'trustscript_published_orders';

	/**
	 * Schema version for the registry table. Increment this if the table structure changes in a future update.
	 * The create_table() method will check this version and perform necessary upgrades.
	 */
	const SCHEMA_VERSION = '1.0';

	/**
	 * Check if the table exists in the database.
	 */
	public static function table_exists() {
		global $wpdb;
		$table = self::get_table_name();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared
		return $wpdb->get_var( $wpdb->prepare( "SHOW TABLES LIKE %s", $table ) ) === $table;
	}

	/**
	 * Create (or upgrade) the registry table.
	 */
	public static function create_table() {
		global $wpdb;

		$installed_version = get_option( 'trustscript_registry_schema_version', '' );
		if ( $installed_version === self::SCHEMA_VERSION && self::table_exists() ) {
			return; 
		}

		$table_name      = esc_sql( self::get_table_name() );
		$charset_collate = $wpdb->get_charset_collate();

		$sql = "CREATE TABLE {$table_name} (
			id               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
			service_id       VARCHAR(64)  NOT NULL COMMENT 'e.g. woocommerce, memberpress',
			source_order_id  VARCHAR(64)  NOT NULL COMMENT 'Order/transaction/booking ID from the source service',
			product_id       VARCHAR(64)  NULL COMMENT 'WooCommerce product ID — NULL for single-product legacy rows',
			product_token    VARCHAR(256) NULL COMMENT 'SHA256 hash generated by plugin — for webhook lookup',
			published_at     DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'UTC time the review was marked as published',
			`trigger`        VARCHAR(32)  NOT NULL DEFAULT 'webhook' COMMENT 'webhook | manual_sync | auto_sync',
			PRIMARY KEY  (id),
			UNIQUE KEY   uq_service_order_product (service_id, source_order_id, product_id),
			KEY          idx_service_id (service_id),
			KEY          idx_product_token (product_token)
		) {$charset_collate};";

		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		dbDelta( $sql );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$old_key_exists = $wpdb->get_var( $wpdb->prepare(
			"SELECT COUNT(*) FROM information_schema.STATISTICS
			 WHERE table_schema = DATABASE()
			   AND table_name   = %s
			   AND index_name   = 'uq_service_order'",
			$table_name
		) );

		if ( $old_key_exists ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$wpdb->query( "ALTER TABLE {$table_name} DROP INDEX uq_service_order" );
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$new_key_exists = $wpdb->get_var( $wpdb->prepare(
			"SELECT COUNT(*) FROM information_schema.STATISTICS
			 WHERE table_schema = DATABASE()
			   AND table_name   = %s
			   AND index_name   = 'uq_service_order_product'",
			$table_name
		) );

		if ( ! $new_key_exists ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table_name} ADD UNIQUE KEY uq_service_order_product (service_id, source_order_id, product_id)" );
		}

		update_option( 'trustscript_registry_schema_version', self::SCHEMA_VERSION );
	}

	/**
	 * Mark an order/product as published in the registry.
	 * 
	 * @param string     $service_id      e.g. 'woocommerce'
	 * @param int|string $source_order_id The WC order ID, MemberPress txn ID, etc.
	 * @param int|string $product_id      The product/item ID within the order. NULL for legacy single-product calls.
	 * @param string     $product_token   SHA256 hash generated by the plugin. NULL for legacy calls.
	 * @param string     $trigger         How it was triggered: 'webhook', 'manual_sync', 'auto_sync'
	 * @return bool True on insert, false if already existed or on DB error.
	 */
	public static function mark_published( $service_id, $source_order_id, $product_id = null, $product_token = null, $trigger = 'webhook' ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$result = $wpdb->query(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"INSERT IGNORE INTO {$table_name} (service_id, source_order_id, product_id, product_token, published_at, `trigger`) VALUES (%s, %s, %s, %s, %s, %s)",
				$service_id,
				(string) $source_order_id,
				$product_id ? (string) $product_id : null,
				$product_token ? (string) $product_token : null,
				gmdate( 'Y-m-d H:i:s' ),
				$trigger
			)
		);

		if ( $result === false ) {
			return false;
		}

		return ( $result > 0 );
	}

	/**
	 * Check if a specific product in an order is already published.
	 * When $product_id is omitted, falls back to order-level check.
	 *
	 * @param string     $service_id
	 * @param int|string $source_order_id
	 * @param int|string $product_id
	 * @return bool
	 */
	public static function is_published( $service_id, $source_order_id, $product_id = null ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		if ( $product_id !== null ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$count = $wpdb->get_var(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"SELECT COUNT(*) FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND product_id = %s LIMIT 1",
					$service_id,
					(string) $source_order_id,
					(string) $product_id
				)
			);
		} else {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$count = $wpdb->get_var(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"SELECT COUNT(*) FROM {$table_name} WHERE service_id = %s AND source_order_id = %s LIMIT 1",
					$service_id,
					(string) $source_order_id
				)
			);
		}

		return ( intval( $count ) > 0 );
	}

	/**
	 * Get all published order IDs for a given service. Useful for syncing and reporting.
	 *
	 * @param string $service_id
	 * @return string[] Array of source_order_id strings.
	 */
	public static function get_published_order_ids( $service_id ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table query, caching handled at application level
		$ids = $wpdb->get_col(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, PluginCheck.Security.DirectDB.UnescapedDBParameter -- Table name is safely generated by get_table_name() using wpdb->prefix and hardcoded constant
				"SELECT source_order_id FROM {$table_name} WHERE service_id = %s",
				$service_id
			)
		);

		return is_array( $ids ) ? $ids : array();
	}

	/**
	 * Check if the number of published products for an order matches the expected count.
	  * This is used to determine if an order is "complete" and can be marked as fully published.
	 *
	 * @param string     $service_id
	 * @param int|string $source_order_id
	 * @param int        $expected_product_count Total number of products in the order.
	 * @return bool True if published product count matches expected count.
	 */
	public static function is_order_complete( $service_id, $source_order_id, $expected_product_count ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$published_count = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT COUNT(*) FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND product_id IS NOT NULL",
				$service_id,
				(string) $source_order_id
			)
		);

		return ( intval( $published_count ) >= intval( $expected_product_count ) );
	}

	/**
	 * Get all published product IDs for a given order. 
	 * Useful for multi-product orders to check which items have been published.
	 *
	 * @param string     $service_id
	 * @param int|string $source_order_id
	 * @return string[] Array of product_id strings.
	 */
	public static function get_published_products( $service_id, $source_order_id ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$ids = $wpdb->get_col(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT product_id FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND product_id IS NOT NULL",
				$service_id,
				(string) $source_order_id
			)
		);

		return is_array( $ids ) ? $ids : array();
	}

	/**
	 * Check if a product token has already been published. This is used for webhook processing to ensure idempotency.
	 * The product token is a SHA256 hash generated by the plugin based on order and product details, 
	 * and included in the webhook payload.
	 *
	 * @param string $product_token SHA256 hash from the webhook request.
	 * @return bool True if this token has already been published.
	 */
	public static function is_product_token_published( $product_token ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$count = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT COUNT(*) FROM {$table_name} WHERE product_token = %s LIMIT 1",
				(string) $product_token
			)
		);

		return ( intval( $count ) > 0 );
	}

	/**
	 * Get the full table name with prefix for use in queries.
	 *
	 * @return string
	 */
	public static function get_table_name() {
		global $wpdb;
		return $wpdb->prefix . self::TABLE_SLUG;
	}
}