<?php
/**
 * TrustScript Order Registry
 *
 * @package TrustScript
 * @since 1.0.0
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class TrustScript_Order_Registry {

	/**
	 * Database table slug for the order registry. The full table name will be {wpdb->prefix} + this slug.
	 */
	const TABLE_SLUG = 'trustscript_published_orders';

	/**
	 * Schema version for the registry table.
	 */
	const SCHEMA_VERSION = '1.0';

	/**
	 * Check if the registry table exists in the database.
	 */
	public static function table_exists() {
		global $wpdb;
		$table = self::get_table_name();
		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.PreparedSQL.NotPrepared
		return $wpdb->get_var( $wpdb->prepare( 'SHOW TABLES LIKE %s', $table ) ) === $table;
	}

	/**
	 * Create or update the registry table schema as needed. 
	 * Should be called on plugin activation and on schema version changes.
	 * 
	 * @since 1.0.0
	 * @return void
	 */

	public static function create_table() {
		global $wpdb;

		$installed_version = get_option( 'trustscript_registry_schema_version', '' );
		if ( $installed_version === self::SCHEMA_VERSION && self::table_exists() ) {
			return;
		}

		$table_name      = esc_sql( self::get_table_name() );
		$charset_collate = $wpdb->get_charset_collate();

		$sql = "CREATE TABLE {$table_name} (
			id               BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
			service_id       VARCHAR(64)  NOT NULL COMMENT 'e.g. woocommerce, memberpress',
			source_order_id  VARCHAR(64)  NOT NULL COMMENT 'Order/transaction/booking ID from the source service',
			product_id       VARCHAR(64)  NULL     COMMENT 'WooCommerce product/variation ID — NULL for single-product legacy rows',
			product_token    VARCHAR(256) NULL     COMMENT 'SHA256 hash generated by plugin — indexed for webhook lookup',
			published_at     DATETIME     NULL     COMMENT 'UTC time the review was published. NULL = review requested but not yet published.',
			`trigger`        VARCHAR(32)  NOT NULL DEFAULT 'webhook' COMMENT 'review_requested | webhook | manual_sync | auto_sync',
			PRIMARY KEY  (id),
			UNIQUE KEY   uq_service_order_product (service_id, source_order_id, product_id),
			KEY          idx_service_id (service_id),
			KEY          idx_product_token (product_token)
		) {$charset_collate};";

		require_once ABSPATH . 'wp-admin/includes/upgrade.php';
		dbDelta( $sql );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$column_info = $wpdb->get_row(
			$wpdb->prepare(
				"SELECT IS_NULLABLE FROM information_schema.COLUMNS
				  WHERE table_schema = DATABASE()
				    AND table_name   = %s
				    AND column_name  = 'published_at'",
				$table_name
			)
		);

		if ( $column_info && 'NO' === $column_info->IS_NULLABLE ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$wpdb->query( "ALTER TABLE {$table_name} MODIFY published_at DATETIME NULL COMMENT 'UTC time the review was published. NULL = review requested but not yet published.'" );
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$old_key_exists = $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM information_schema.STATISTICS
				  WHERE table_schema = DATABASE()
				    AND table_name   = %s
				    AND index_name   = 'uq_service_order'",
				$table_name
			)
		);

		if ( $old_key_exists ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange, WordPress.DB.PreparedSQL.InterpolatedNotPrepared
			$wpdb->query( "ALTER TABLE {$table_name} DROP INDEX uq_service_order" );
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$new_key_exists = $wpdb->get_var(
			$wpdb->prepare(
				"SELECT COUNT(*) FROM information_schema.STATISTICS
				  WHERE table_schema = DATABASE()
				    AND table_name   = %s
				    AND index_name   = 'uq_service_order_product'",
				$table_name
			)
		);

		if ( ! $new_key_exists ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.PreparedSQL.InterpolatedNotPrepared, WordPress.DB.DirectDatabaseQuery.NoCaching, WordPress.DB.DirectDatabaseQuery.SchemaChange
			$wpdb->query( "ALTER TABLE {$table_name} ADD UNIQUE KEY uq_service_order_product (service_id, source_order_id, product_id)" );
		}

		update_option( 'trustscript_registry_schema_version', self::SCHEMA_VERSION );
	}

	/**
	 * Record a product token in the registry with published_at = NULL to indicate
	 * "review requested but not yet published" state.
	 *
	 * @param string     $service_id      e.g. 'woocommerce'
	 * @param int|string $source_order_id WC order ID
	 * @param int|string $product_id      WC product/variation ID
	 * @param string     $product_token   SHA256 hash generated by the plugin
	 * @return bool True on fresh insert, false if row already existed or on DB error.
	 */
	public static function record_product_token( $service_id, $source_order_id, $product_id, $product_token ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$result = $wpdb->query(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"INSERT IGNORE INTO {$table_name}
				 (service_id, source_order_id, product_id, product_token, published_at, `trigger`)
				 VALUES (%s, %s, %s, %s, NULL, 'review_requested')",
				$service_id,
				(string) $source_order_id,
				(string) $product_id,
				$product_token
			)
		);

		return ( $result !== false && $result > 0 );
	}

	/**
	 * Mark a product in an order as published by setting published_at to the current time.
	 *
	 * @param string     $service_id      e.g. 'woocommerce'
	 * @param int|string $source_order_id The WC order ID, MemberPress txn ID, etc.
	 * @param int|string $product_id      The product/item ID within the order. NULL for legacy single-product calls.
	 * @param string     $product_token   SHA256 hash generated by the plugin. NULL for legacy calls.
	 * @param string     $trigger         How it was triggered: 'webhook' | 'manual_sync' | 'auto_sync'
	 * @return bool True if a row was updated or inserted, false on DB error.
	 */
	public static function mark_published( $service_id, $source_order_id, $product_id = null, $product_token = null, $trigger = 'webhook' ) {
		global $wpdb;

		$table_name    = esc_sql( self::get_table_name() );
		$published_now = gmdate( 'Y-m-d H:i:s' );

		if ( $product_id !== null ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$updated = $wpdb->query(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"UPDATE {$table_name}
					 SET published_at = %s, `trigger` = %s
					 WHERE service_id       = %s
					   AND source_order_id  = %s
					   AND product_id       = %s
					   AND published_at IS NULL
					 LIMIT 1",
					$published_now,
					$trigger,
					$service_id,
					(string) $source_order_id,
					(string) $product_id
				)
			);

			if ( $updated !== false && $updated > 0 ) {
				return true;
			}
		}

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$result = $wpdb->query(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"INSERT IGNORE INTO {$table_name} (service_id, source_order_id, product_id, product_token, published_at, `trigger`) VALUES (%s, %s, %s, %s, %s, %s)",
				$service_id,
				(string) $source_order_id,
				$product_id ? (string) $product_id : null,
				$product_token ? (string) $product_token : null,
				$published_now,
				$trigger
			)
		);

		if ( $result === false ) {
			return false;
		}

		return ( $result > 0 );
	}

	/**
	 * Check if an order (or specific product within an order) has been published.
	 *
	 * @param string     $service_id
	 * @param int|string $source_order_id
	 * @param int|string $product_id
	 * @return bool
	 */
	public static function is_published( $service_id, $source_order_id, $product_id = null ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		if ( $product_id !== null ) {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$count = $wpdb->get_var(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"SELECT COUNT(*) FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND product_id = %s AND published_at IS NOT NULL LIMIT 1",
					$service_id,
					(string) $source_order_id,
					(string) $product_id
				)
			);
		} else {
			// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
			$count = $wpdb->get_var(
				$wpdb->prepare(
					// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
					"SELECT COUNT(*) FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND published_at IS NOT NULL LIMIT 1",
					$service_id,
					(string) $source_order_id
				)
			);
		}

		return ( intval( $count ) > 0 );
	}

	/**
	 * Get all source_order_id values for a given service that have at least one published product.
	 *
	 * @param string $service_id
	 * @return string[] Array of source_order_id strings.
	 */
	public static function get_published_order_ids( $service_id ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching -- Custom table query, caching handled at application level
		$ids = $wpdb->get_col(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared, PluginCheck.Security.DirectDB.UnescapedDBParameter -- Table name is safely generated by get_table_name() using wpdb->prefix and hardcoded constant
				"SELECT source_order_id FROM {$table_name} WHERE service_id = %s AND published_at IS NOT NULL",
				$service_id
			)
		);

		return is_array( $ids ) ? $ids : array();
	}

	/**
	 * Check if the number of published products for an order matches the expected count.
	 *
	 * @param string     $service_id
	 * @param int|string $source_order_id
	 * @param int        $expected_product_count Total number of products in the order.
	 * @return bool True if published product count matches expected count.
	 */
	public static function is_order_complete( $service_id, $source_order_id, $expected_product_count ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$published_count = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT COUNT(*) FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND product_id IS NOT NULL AND published_at IS NOT NULL",
				$service_id,
				(string) $source_order_id
			)
		);

		return ( intval( $published_count ) >= intval( $expected_product_count ) );
	}

	/**
	 * Get all published product IDs for a given order. 
	 * Only returns products that have been marked as published (published_at IS NOT NULL).
	 *
	 * @param string     $service_id
	 * @param int|string $source_order_id
	 * @return string[] Array of product_id strings.
	 */
	public static function get_published_products( $service_id, $source_order_id ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$ids = $wpdb->get_col(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT product_id FROM {$table_name} WHERE service_id = %s AND source_order_id = %s AND product_id IS NOT NULL AND published_at IS NOT NULL",
				$service_id,
				(string) $source_order_id
			)
		);

		return is_array( $ids ) ? $ids : array();
	}

	/**
	 * Check if a product token has already been published. This is used by the
	 * webhook handler to reject duplicate publish attempts.
	 *
	 * @param string $product_token SHA256 hash from the webhook request.
	 * @return bool True if this token has already been published.
	 */
	public static function is_product_token_published( $product_token ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$count = $wpdb->get_var(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT COUNT(*) FROM {$table_name} WHERE product_token = %s AND published_at IS NOT NULL LIMIT 1",
				(string) $product_token
			)
		);

		return ( intval( $count ) > 0 );
	}

	/**
	 * Find the source_order_id and product_id associated with a given product token, if it exists.
	 * Used for webhook processing to link back to the original order and product.
	 *
	 * @param string $product_token SHA256 hash from the webhook request.
	 * @return array|false [ source_order_id (int), product_id (int) ] or false if not found.
	 */
	public static function find_by_product_token( $product_token ) {
		global $wpdb;

		$table_name = esc_sql( self::get_table_name() );

		// phpcs:ignore WordPress.DB.DirectDatabaseQuery.DirectQuery, WordPress.DB.DirectDatabaseQuery.NoCaching
		$row = $wpdb->get_row(
			$wpdb->prepare(
				// phpcs:ignore WordPress.DB.PreparedSQL.InterpolatedNotPrepared
				"SELECT source_order_id, product_id FROM {$table_name} WHERE product_token = %s LIMIT 1",
				(string) $product_token
			)
		);

		if ( ! $row || ! $row->source_order_id ) {
			return false;
		}

		return array( intval( $row->source_order_id ), intval( $row->product_id ) );
	}

	/**
	 * Get the full table name with prefix for use in queries.
	 *
	 * @return string
	 */
	public static function get_table_name() {
		global $wpdb;
		return $wpdb->prefix . self::TABLE_SLUG;
	}
}
